export const FPS_CONSTANTS = {
  GRAVITY: 30,
  STEPS_PER_FRAME: 5,

  // プレイヤー
  PLAYER_SPEED: 25,
  PLAYER_JUMP_HEIGHT: 15,
  PLAYER_CAPSULE_RADIUS: 0.35,
  PLAYER_CAPSULE_START_Y: 0.35,
  PLAYER_CAPSULE_END_Y: 1.0,
  FLOOR_NORMAL_Y_THRESHOLD: 0.15,
  RESPAWN_Y_THRESHOLD: -25,

  // カメラ
  CAMERA_FOV: 70,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 1000,

  // ボール
  NUM_SPHERES: 100,
  SPHERE_RADIUS: 0.2,
  SPHERE_BOUNCE_DAMPING: 1.5,
  THROW_BASE_IMPULSE: 15,
  THROW_MAX_EXTRA_IMPULSE: 30,

  // 霧
  FOG_COLOR: 0x88ccee as number,
  FOG_NEAR: 0,
  FOG_FAR: 500,

  // スポーン地点
  SPAWN_X: 0,
  SPAWN_Y: -1.5,
  SPAWN_Z: 0,
} as const;
